import { useMemo, useState } from 'react'
import './App.css'

const categories = ['All dishes', 'Coffee & tea', 'Fresh drinks', 'Breakfast', 'Mains', 'Pizza & burgers', 'Salads']
const initialMenuItems = [
  ['Canoe Special', 'Mains', '1500', 'Our house signature, served with a generous plate of sides.'], ['Special Tibs', 'Mains', '640', 'Tender, seasoned pieces with peppers and onions.'], ['Gomen Kitifo', 'Mains', '270', 'A classic Ethiopian favorite with house-seasoned greens.'], ['Spaghetti with Meat', 'Mains', '300', 'Comforting pasta finished with our rich meat sauce.'], ['Rice with Vegetable', 'Mains', '220', 'Steamed rice with a colorful vegetable sauté.'], ['Chicken Firfir', 'Mains', '240', 'Soft injera tossed with spiced chicken and berbere.'],
  ['Special Club Sandwich', 'Pizza & burgers', '520', 'Stacked with fresh greens, cheese and our house filling.'], ['Special Double Burger', 'Pizza & burgers', '695', 'Two juicy patties, cheese, lettuce and tomato.'], ['Chicken Burger', 'Pizza & burgers', '520', 'Crisp chicken, fresh salad and a toasted bun.'], ['Special Pizza', 'Pizza & burgers', '530', 'A generous, cheesy house favorite.'], ['Vegetable Pizza', 'Pizza & burgers', '490', 'Fresh vegetables, herbs and melted cheese.'], ['Chicken Soup', 'Mains', '370', 'Warm, deeply savory and made for slow lunches.'], ['Vegetable Soup', 'Mains', '220', 'A bright, comforting bowl of seasonal vegetables.'], ['Fish Soup', 'Mains', '320', 'Lightly spiced and full of delicate flavor.'],
  ['Egg Sandwich', 'Breakfast', '260', 'Soft egg and fresh fillings in toasted bread.'], ['Special Egg Sandwich', 'Breakfast', '340', 'Our fuller, richer take on a morning classic.'], ['Egg Firfir', 'Breakfast', '270', 'Torn injera folded through warm seasoned egg.'], ['Pancake', 'Breakfast', '220', 'Golden, tender and made for a slow morning.'], ['Special Omelet', 'Breakfast', '290', 'A fluffy omelet with the works.'], ['Fetira', 'Breakfast', '220', 'Flaky, buttery and freshly prepared.'],
  ['Cappuccino', 'Coffee & tea', '200', 'Velvety espresso, steamed milk and a soft crown.'], ['Macchiato', 'Coffee & tea', '40', 'A short espresso touched with silky milk.'], ['Special Tea', 'Coffee & tea', '80', 'Fragrant tea blended with a Canoe touch.'], ['Ginger Tea', 'Coffee & tea', '90', 'Bright ginger warmth, served hot.'], ['Lemon Tea', 'Coffee & tea', '55', 'A clean, citrusy cup.'],
  ['Special Mojito', 'Fresh drinks', '185', 'A sparkling, minty cooler with fresh citrus.'], ['Strawberry Mojito', 'Fresh drinks', '160', 'Fresh strawberry, mint and a lively finish.'], ['Orange Mojito', 'Fresh drinks', '160', 'Bright orange with a cooling mint lift.'], ['Avocado Juice', 'Fresh drinks', '185', 'Creamy, cool and blended to order.'], ['Pineapple Juice', 'Fresh drinks', '220', 'Fresh tropical sweetness in every glass.'], ['Mixed Juice', 'Fresh drinks', '210', 'A colorful blend of the day’s freshest fruit.'],
  ['Fruit Salad', 'Salads', '370', 'Freshly cut fruit, bright and naturally sweet.'], ['Mixed Salad', 'Salads', '300', 'Crisp greens and colorful garden vegetables.'], ['Avocado Salad', 'Salads', '290', 'Creamy avocado over fresh, crunchy greens.'], ['Russian Salad', 'Salads', '400', 'A generous, creamy classic.'],
].map(([name, category, price, description]) => ({ name, category, price, description }))

function AdminTable({ items, editingItem, setEditingItem, updateItem, removeItem }) {
  return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Dish</th><th>Category</th><th>Price</th><th>Description</th><th>Actions</th></tr></thead><tbody>{items.map((item) => {
    if (editingItem === item.name) {
          return <tr key={item.name}><td><input aria-label={`Edit ${item.name} name`} value={item.name} onChange={(event) => { updateItem(item.name, 'name', event.target.value); setEditingItem(event.target.value) }} /></td><td><select aria-label={`Edit ${item.name} category`} value={item.category} onChange={(event) => updateItem(item.name, 'category', event.target.value)}>{categories.slice(1).map((category) => <option key={category}>{category}</option>)}</select></td><td><input aria-label={`Edit ${item.name} price`} value={item.price} onChange={(event) => updateItem(item.name, 'price', event.target.value)} /></td><td><input aria-label={`Edit ${item.name} description`} value={item.description} onChange={(event) => updateItem(item.name, 'description', event.target.value)} /></td><td><button className="admin-action primary" type="button" onClick={() => setEditingItem(null)}>Save</button></td></tr>
    }
    return <tr key={item.name}><td>{item.name}</td><td>{item.category}</td><td>{item.price}</td><td>{item.description}</td><td><button className="admin-action" type="button" onClick={() => setEditingItem(item.name)}>Edit</button><button className="admin-action danger" type="button" onClick={() => removeItem(item.name)}>Delete</button></td></tr>
  })}</tbody></table></div>
}

function CommentsTable({ comments, removeComment }) {
  return <section className="comments-admin" aria-labelledby="comments-heading"><div className="comments-heading"><div><p className="eyebrow">Guest feedback</p><h3 id="comments-heading">Customer comments</h3></div><span>{comments.length} {comments.length === 1 ? 'comment' : 'comments'}</span></div>{comments.length ? <div className="comments-list">{comments.map((comment) => <article className="comment-item" key={comment.id}><div className="comment-meta"><strong>{comment.name || 'Anonymous guest'}</strong><span>{comment.rating ? `${comment.rating}/5 stars` : 'No rating'}</span></div><p>{comment.text}</p><button className="admin-action danger" type="button" onClick={() => removeComment(comment.id)}>Delete comment</button></article>)}</div> : <p className="comments-empty">Customer comments will appear here after guests submit a review.</p>}</section>
}

function App() {
  const [menuItems, setMenuItems] = useState(initialMenuItems)
  const [activeCategory, setActiveCategory] = useState('All dishes')
  const [query, setQuery] = useState('')
  const [rating, setRating] = useState(0)
  const [reviewSubmitted, setReviewSubmitted] = useState(false)
  const [comments, setComments] = useState([])
  const [showAdminLogin, setShowAdminLogin] = useState(false)
  const [isAdmin, setIsAdmin] = useState(false)
  const [adminEmail, setAdminEmail] = useState('')
  const [adminPassword, setAdminPassword] = useState('')
  const [loginError, setLoginError] = useState('')
  const [editingItem, setEditingItem] = useState(null)
  const [newItem, setNewItem] = useState({ name: '', category: 'Mains', price: '', description: '' })

  const filteredItems = useMemo(() => menuItems.filter((item) => {
    const matchesCategory = activeCategory === 'All dishes' || item.category === activeCategory
    return matchesCategory && `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase())
  }), [activeCategory, menuItems, query])
  const updateItem = (itemName, field, value) => setMenuItems((items) => items.map((item) => item.name === itemName ? { ...item, [field]: value } : item))
  const removeItem = (itemName) => setMenuItems((items) => items.filter((item) => item.name !== itemName))
  const removeComment = (commentId) => setComments((items) => items.filter((item) => item.id !== commentId))
  const addItem = (event) => {
    event.preventDefault()
    if (!newItem.name.trim() || !newItem.price.trim() || !newItem.description.trim()) return
    setMenuItems((items) => [...items, { ...newItem, name: newItem.name.trim(), price: newItem.price.trim(), description: newItem.description.trim() }])
    setNewItem({ name: '', category: 'Mains', price: '', description: '' })
  }
  const handleAdminLogin = (event) => {
    event.preventDefault()
    if (adminEmail === 'a@gmail.com' && adminPassword === '1111') { setIsAdmin(true); setShowAdminLogin(false); setLoginError('') } else setLoginError('Incorrect email or password.')
  }

  return <main className="menu-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="Canoe home"><span className="brand-mark">c</span><span>canoe</span></a><div className="topbar-note"><span className="status-dot" /> Open today <strong>8:00 — 22:00</strong></div><button className="order-button" type="button" onClick={() => document.querySelector('.menu-grid')?.scrollIntoView({ behavior: 'smooth' })}>View menu <span>↓</span></button></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Addis Ababa · Est. 2014</p><h1>Good food,<br /><em>good company.</em></h1><p className="hero-intro">A warm table for bright mornings, long lunches, and evenings that take their time.</p></div><div className="hero-stamp"><span>CAFE</span><strong>CANOE</strong><small>eat · drink · linger</small></div></section>
    <section className="menu-section" aria-label="Canoe menu"><div className="section-heading"><div><p className="eyebrow">From our kitchen</p><h2>Find your favorite</h2></div><p className="item-count">{filteredItems.length} dishes</p></div><div className="search-wrap"><span className="search-icon" aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search dishes, drinks, or ingredients" aria-label="Search menu" />{query && <button className="clear-search" type="button" onClick={() => setQuery('')} aria-label="Clear search">×</button>}<kbd>⌘ K</kbd></div><nav className="category-nav" aria-label="Menu categories">{categories.map((category) => <button className={activeCategory === category ? 'active' : ''} key={category} onClick={() => setActiveCategory(category)} type="button">{category}</button>)}</nav>{filteredItems.length ? <div className="menu-grid">{filteredItems.map((item, index) => <article className="menu-item" key={item.name} style={{ '--delay': `${index * 35}ms` }}><div className="item-top"><span className="item-category">{item.category}</span><span className="item-price">{item.price}</span></div><h3>{item.name}</h3><p>{item.description}</p><button className="add-button" type="button" aria-label={`Add ${item.name}`}>+</button></article>)}</div> : <div className="empty-state"><span>⌕</span><h3>No dishes found</h3><p>Try another search or browse all dishes.</p><button type="button" onClick={() => { setQuery(''); setActiveCategory('All dishes') }}>Reset menu</button></div>}</section>
    <section className="review-section" aria-labelledby="review-heading"><div className="review-copy"><p className="eyebrow">A word from you</p><h2 id="review-heading">How was your visit?</h2><p>Tell us what you enjoyed, or what we can make even better.</p></div>{reviewSubmitted ? <div className="review-success" role="status"><span aria-hidden="true">✓</span><h3>Thank you for sharing.</h3><p>Your review means a lot to the Canoe team.</p><button type="button" onClick={() => setReviewSubmitted(false)}>Write another review</button></div> : <form className="review-form" onSubmit={(event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); setComments((items) => [...items, { id: Date.now(), name: formData.get('name').trim(), text: formData.get('comment').trim(), rating }]); setReviewSubmitted(true); setRating(0); event.currentTarget.reset() }}><fieldset><legend>Rate your visit</legend><div className="star-rating">{[1, 2, 3, 4, 5].map((star) => <button className={star <= rating ? 'selected' : ''} key={star} type="button" onClick={() => setRating(star)} aria-label={`${star} star${star === 1 ? '' : 's'}`} aria-pressed={star === rating}>★</button>)}</div></fieldset><label className="review-field"><span>Name <small>(optional)</small></span><input name="name" type="text" placeholder="Your name" /></label><label className="review-field"><span>Comment</span><textarea name="comment" required placeholder="Share your experience" rows="4" /></label><button className="review-submit" type="submit">Submit review <span>↗</span></button></form>}</section>
    <footer><span>CANOE CAFE</span><span>Made for lingering.</span><button className="admin-login-button" type="button" onClick={() => { setShowAdminLogin(true); setLoginError('') }}>Admin login</button></footer>
    {showAdminLogin && <div className="admin-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowAdminLogin(false) }}><form className="admin-login" onSubmit={handleAdminLogin}><button className="admin-close" type="button" onClick={() => setShowAdminLogin(false)} aria-label="Close admin login">×</button><p className="eyebrow">Canoe management</p><h2>Admin login</h2><label className="admin-field"><span>Email</span><input autoFocus type="email" value={adminEmail} onChange={(event) => setAdminEmail(event.target.value)} required /></label><label className="admin-field"><span>Password</span><input type="password" value={adminPassword} onChange={(event) => setAdminPassword(event.target.value)} required /></label>{loginError && <p className="login-error" role="alert">{loginError}</p>}<button className="admin-submit" type="submit">Login <span>↗</span></button></form></div>}
    {isAdmin && <section className="admin-panel" aria-labelledby="admin-heading"><div className="admin-panel-heading"><div><p className="eyebrow">Signed in as admin</p><h2 id="admin-heading">Manage menu</h2></div><button className="admin-logout" type="button" onClick={() => { setIsAdmin(false); setEditingItem(null) }}>Log out</button></div><form className="add-item-form" onSubmit={addItem}><h3>Add a dish</h3><div className="admin-form-grid"><input aria-label="New dish name" placeholder="Dish name" value={newItem.name} onChange={(event) => setNewItem({ ...newItem, name: event.target.value })} /><select aria-label="New dish category" value={newItem.category} onChange={(event) => setNewItem({ ...newItem, category: event.target.value })}>{categories.slice(1).map((category) => <option key={category}>{category}</option>)}</select><input aria-label="New dish price" placeholder="Price" value={newItem.price} onChange={(event) => setNewItem({ ...newItem, price: event.target.value })} /><input aria-label="New dish description" placeholder="Description" value={newItem.description} onChange={(event) => setNewItem({ ...newItem, description: event.target.value })} /><button className="admin-action primary" type="submit">Add dish</button></div></form><AdminTable items={menuItems} editingItem={editingItem} setEditingItem={setEditingItem} updateItem={updateItem} removeItem={removeItem} /><CommentsTable comments={comments} removeComment={removeComment} /></section>}
  </main>
}

export default App
